#!/usr/bin/env bash
# simple screenlocker using swaylock that creates a blurred screenshot to overlay
PICTURE=/tmp/i3lock.png
SCREENSHOT="grim $PICTURE"
BLUR="5x4"
$SCREENSHOT
magick $PICTURE -blur $BLUR $PICTURE
swaylock -i $PICTURE
shred $PICTURE
rm $PICTURE
